# config for custom patched binary

# theme = "gruvbox-material"
theme = "gruvbox_material_dark_hard"

# =============================================================================

[editor]
clipboard-provider = "win32-yank"
cursor-shape.insert = "bar"
file-picker.hidden = false
rulers = [80, 120]

# =============================================================================

[editor.lsp]
display-inlay-hints = false

# =============================================================================

[keys.select]
"f" = ["normal_mode", "collapse_selection"]

[keys.normal]
"C-c" = "@%y"
"A-j" = "shrink_selection"
"A-k" = "expand_selection"

[keys.normal.';']
"e" = ":write-quit-all"
"w" = ":write-all"
"n" = ":quit-all!"
"s" = "search"

[keys.normal.space.b]
"d" = ":buffer-close"
"o" = ":buffer-close-others"

# =============================================================================
# TODO
# b.in selection mode move the selected content with alt + h,j,k,l
# c.add old files picker, session retrival
# d.when closing and opening files the cursor should remember the previous
# position the same goes with copying the entire file
# e.mim does not work as intended (done)
# f.There is a patch for 'D' in evil helix repo
# g.paste does not work as intended
# =============================================================================
