[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.typescript-language-server.config]
hostInfo = "helix"
provideFormatter = false
completions = { completeFunctionCalls = true }
preferences = { includeCompletionsWithSnippetText = true, includeCompletionsWithInsertText = true }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "oxfmt-language-server"]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "oxlint-language-server",
  "oxfmt-language-server",
  "typescript-language-server",
]
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "oxfmt-language-server"]
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "oxfmt-language-server"]
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
